"""Request and response schemas for the REST API."""

from datetime import datetime
from typing import Literal, Optional

from pydantic import BaseModel, Field


class DeliveryRequest(BaseModel):
    # Generated by the backend (ORD-001, ORD-002, ...) when omitted.
    order_id: Optional[str] = Field(default=None, min_length=1, max_length=64)
    destination: str = Field(min_length=1)


class DeliveryResponse(BaseModel):
    status: Literal["queued"]
    order_id: str


class RobotStatus(BaseModel):
    state: str
    battery: Optional[float]
    current_order: Optional[str]
    last_update: Optional[datetime]
    connected: bool


class DestinationsResponse(BaseModel):
    destinations: list[str]


class HealthResponse(BaseModel):
    api: Literal["ok"]
    rosbridge: Literal["connected", "disconnected"]
    mode: Literal["ros", "fake"]
