from enum import Enum


class MissionState(Enum):
    IDLE = "IDLE"
    QUEUED = "QUEUED"
    NAVIGATING = "NAVIGATING"
    PICKING_UP = "PICKING_UP"
    CHANGING_FLOOR = "CHANGING_FLOOR"
    DELIVERING = "DELIVERING"
    RETURNING = "RETURNING"
    DOCKING = "DOCKING"
    DOCKED = "DOCKED"
